Test builder tests: 1
Canditech-io/e2e pull request #10
Opened 2023-10-22 16:59 UTC by KnaanBrazCanditech

2023-10-22 20:49 UTC, eyalCanditech approved these changes

2023-10-22 20:49 UTC, eyalCanditech commented on playwright.config.ts
> +    headless: false,
isn't headless false should be used for debugging and development?

2023-10-23 06:22 UTC, KnaanBrazCanditech commented on playwright.config.ts
> +    headless: false,
Yeah yeah... leftover

2023-10-30 19:18 UTC, alexCanditech requested changes

2023-10-31 08:22 UTC, KnaanBrazCanditech commented on consts/dataTestIds.ts
> +    testCardDeleteButton: '.menu-item:last-child'
This is the goal, using data-testid. All of this selector should be converted to data-testid. 
This is the way the outsource guys will work. We will implement the testids later.

2023-10-31 08:25 UTC, KnaanBrazCanditech commented on drivers/BasePage.driver.ts
> +    await this.page.evaluate(`window.isAuthenticated = ${isAuthenticated}`);
It is not that simple. We can have more then one BaseDriver instance per test and they are not sharing their state of cause. I tough this is a good enough method for now.

2023-10-31 08:26 UTC, KnaanBrazCanditech commented on drivers/BasePage.driver.ts
Yeah yeah.. by mistake

2023-10-31 08:34 UTC, KnaanBrazCanditech commented on drivers/pages/tests.driver.ts
> +    await this.page.waitForTimeout(1000);
Tried for serval minutes. Decided this is not worth the time. 
In this case this is just make the action faster. In case we didn't wait enough there will be more cards that we are later gonna filter.

2023-10-31 08:37 UTC, KnaanBrazCanditech commented on tests/test-builder/testContent.sanity.spec.ts
> +    const testName = `${TEST_NAME_PREFIX}${Date.now()}`;
You are right but. I meant to add a task to delete all test with this prefix after all the tests the used this prefix. Just to make sure that if something went wrong during the tests we don't leaving leftovers of to delete everything in the end instead of after every tests. I didn't do it yet but I thought it is not bad to have it so I left it.

2023-10-31 08:38 UTC, KnaanBrazCanditech commented on tests/test-collection/tests.sanity.spec.ts
> +});
Only = true. In future PRs will be changed to options

2023-10-31 08:39 UTC, KnaanBrazCanditech commented on drivers/BasePage.driver.ts
I was continuing with the current state but you are right, let's change it. 
I dedicated a whole PR for that

2023-10-31 08:41 UTC, KnaanBrazCanditech commented on drivers/pages/login.driver.ts
> -    await this.page.goto(routeFactory.login(), { waitUntil: 'networkidle' });
Leave it for now. The next prs has some additional improvements

2023-10-31 09:39 UTC, alexCanditech commented on drivers/BasePage.driver.ts
> +    await this.page.evaluate(`window.isAuthenticated = ${isAuthenticated}`);
I would recommend we test something else here, that we know only signed in users see, for example the existence of the profile (just an example)

This is too artificial IMO

2023-10-31 09:41 UTC, alexCanditech commented on drivers/pages/tests.driver.ts
> +    await this.page.waitForTimeout(1000);
I disagree, we should have no timers in tests, have you tried simply awaiting for the selector?

2023-10-31 09:57 UTC, alexCanditech commented on consts/dataTestIds.ts
> +    testCardDeleteButton: '.menu-item:last-child'
I am challenging that decision, I don't think this is the most efficient approach, the most efficient IMO is to enable testing against localhost so that we can add test ids while we develop the tests and avoid having to revisit all tests. It will save us a lot of time

cc @eyalCanditech

2023-10-31 16:41 UTC, merged