Test builder tests 2: welcome page tests
Canditech-io/e2e pull request #11
Opened 2023-10-24 12:54 UTC by KnaanBrazCanditech

2023-10-24 13:16 UTC, eyalCanditech commented on tests/test-builder/testContent.sanity.spec.ts
> +    await contentDriver.createQuestion(/* taskIndex */ 0, 'open');
few other more straightforward readability options here:
const taskIndex = 0;
await contentDriver.createQuestion(taskIndex, 'open');

another option is to change the signature of createQuestion to interface
{
taskIndex: int,
...
}

2023-10-24 13:19 UTC, eyalCanditech commented on drivers/components/welcomePageConfig.driver.ts
> +    await this.page.click(dataTestIdsSelectors.components.welcomePageConfig.introShowMenuButton); // to save the changes
Style:
put the comment above the line and not on the same line

another option is to create a helper method;
async saveXXX() {
  await this.page.click(dataTestIdsSelectors.components.welcomePageConfig.introShowMenuButton);
}

2023-10-24 13:20 UTC, eyalCanditech commented on drivers/components/welcomePageConfig.driver.ts
> +  async init () {
why not explicitly set function visibility to public?
are we trying to save keystrokes?

2023-10-30 19:41 UTC, alexCanditech requested changes

2023-10-30 19:41 UTC, alexCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    await wait(300); // Takes time for the element to update
Please remove the timeout and use this approach instead: https://playwright.dev/docs/test-assertions#locator-assertions-to-have-value

We should wait until the text gets that value and possibly set a timeout if we expect it to take long

2023-10-30 19:41 UTC, alexCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    expect(editedText).toEqual(newTitle);
Thanks for sharing about soft assertions, TIL. I think they make sense in complex tests with multiple stages:

```
// when 1
// expect soft assertion 1

// and then when 2
// expect soft assertion 2
```

In this case where the conditions are the same we can also use a `beforeAll` and have 2 tests:

```ts
test.describe('when the page title is edited', () => {
  const welcomePageConfigDriver = await testBuilderDriver.components.welcomePageConfig();
  const newTitle = 'edited text' + Date.now();

  test.beforeAll(async () => {
    await welcomePageConfigDriver.editTitleOrText(newTitle, 'title');
  })

  test('dispatches the "edited text" gtm event', async () => {
    await gtmService.expect('edited text');
  })

  test('updates the page title', async () => {
    await expect(welcomePageConfigDriver.getTitleOrText('title')).toHaveText(newTitle)
  })
})
```
 

I am not sure if soft assertions is preferable here and it probably depends how the report is shown and whether it is very clear what assertions pass/fail.

My vote is to separate tests even if more verbose but I am ok with using soft assertions as long as the test report clearly shows what assertions pass/fail

2023-10-30 19:41 UTC, alexCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    await gtmService.expect('replaced logo');
same as above, we should definitely improve with soft assertions or split conditions for better reporting

2023-10-30 19:41 UTC, alexCanditech commented on utils/waiterUtils.ts
> +export const wait = async (time: number) => {
pls remove this one once the previous comments are addressed

2023-10-31 08:11 UTC, KnaanBrazCanditech commented on consts/dataTestIds.ts
> +      uploadButton: '.uploadBtn'
This is the goal of this file. The css selectors are just temporary. Because also locally i'm working with test env I have to use the css first then to convert it to data-testid. We have already have asana task.

2023-10-31 08:13 UTC, KnaanBrazCanditech commented on drivers/components/mediaUploadModalDriver.ts
> +    const fileInputSelector = `${dataTestIdsSelectors.components.mediaUploadModal.container} input[type=file]`;
First no. Second when we will have the data-testid on the input this won't be a problem event if we will

2023-10-31 09:18 UTC, KnaanBrazCanditech commented on tests/test-builder/testContent.sanity.spec.ts
> +  appTest('Check add from library gtm event', TestBuilderPageDriver, '', async ({ driver: testBuilderDriver, gtmService }) => {
I'll will consider. wanted this to be one liner.

2023-10-31 09:20 UTC, KnaanBrazCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    await wait(300); // Takes time for the element to update
Don't have access to `page` but I will try

2023-10-31 09:31 UTC, alexCanditech commented on consts/dataTestIds.ts
> +      uploadButton: '.uploadBtn'
We should 100% enable the ability to work with the local env when developing, I assumed we do that, what is our reasoning here? IMO we are wasting a lot of time with the current setup

cc @eyalCanditech

2023-10-31 09:34 UTC, alexCanditech commented on tests/test-builder/testContent.sanity.spec.ts
> +  appTest('Check add from library gtm event', TestBuilderPageDriver, '', async ({ driver: testBuilderDriver, gtmService }) => {
Readability is more important I think

2023-10-31 09:37 UTC, alexCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    await wait(300); // Takes time for the element to update
I think you should just

```ts
await expect(driver.getTitleOrText('title')).toHaveText(newTitle)
```

2023-10-31 09:59 UTC, alexCanditech commented on drivers/components/mediaUploadModalDriver.ts
> +    const fileInputSelector = `${dataTestIdsSelectors.components.mediaUploadModal.container} input[type=file]`;
I will leave this unresolved for now as it's related to the general discussion about data test ids

2023-10-31 10:05 UTC, eyalCanditech commented on tests/test-builder/welcomePage.sanity.spec.ts
> +    expect(editedText).toEqual(newTitle);
Good idea that you will also take some of the tests
We have the onboarding tests coming up next

2023-10-31 10:54 UTC, KnaanBrazCanditech commented on tests/test-builder/testContent.sanity.spec.ts
> +  appTest('Check add from library gtm event', TestBuilderPageDriver, '', async ({ driver: testBuilderDriver, gtmService }) => {
I agree unless this is a very very commonly used method. The you know it by heart. Then readability is not an issue. 
The goal in those cases should be clean, ascetic and easy. I know you may not agree on that point.

2023-10-31 16:41 UTC, merged