Gtm as a service + additional tests
Canditech-io/e2e pull request #9
Opened 2023-10-18 09:28 UTC by KnaanBrazCanditech

- Introducing gtm as a service. appTest callback will be expose to gtmService (in the future maybe more services). 
The instance will be able to better track the events in case of an event occurring twice at the same test. 
- Two additional tests

2023-10-18 09:32 UTC, KnaanBrazCanditech commented on services/gtm/service.ts
> +
Pretty much the same. 
Follow `eventsCount` so see changes.

2023-10-30 18:36 UTC, alexCanditech requested changes

2023-10-31 08:58 UTC, KnaanBrazCanditech commented on tests/test-factory.ts
> +      gtmService: new GtmService(driverInstance as IBaseDriver)
Each test should have it's own instance of the service. How do you suggest, without having annoying boilerplates, to provide test access to this service instance? When I needed to share a variable between the beforeEach I had var outside the scope and assign to it every beforeEach run. Not very nice.... 
Also fyi `beforeAll` doesn't have `page` access which I currently need

2023-10-31 09:01 UTC, KnaanBrazCanditech commented on services/gtm/service.ts
> +export class GtmService {
I need an instance of it. It can't be static. Also it make sense to me to have class for gtm instead of helper functions. Helper function doesn't have context. You consume it without context so you need to have the context in the method name.

2023-10-31 09:07 UTC, KnaanBrazCanditech commented on tests/candidates/assessment-candidate.sanity.spec.ts
> +appTest('Test candidate page load', CandidatePageDriver, assessmentCandidateUrl, async ({ gtmService }) => {
You will see next. Gtm are just one of the assertions. All of the tests execution part are assertions by themselves. If something goes wrong this test will be stuck and will fail. So the assert after the execution is small part of the test. I won't make the test about the event. I will add more asserts to verify additional stuff to make sure to action executed as it should.

2023-10-31 16:42 UTC, merged